services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: file_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build: ./auth
    environment:
      DATABASE_DSN: postgresql://postgres:password@db:5432/file_storage
      HOST: 0.0.0.0
      PORT: 5001
      SECRET_KEY: your-secret-key-here
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy

  storage:
    build: ./storage
    environment:
      DATABASE_DSN: postgresql://postgres:password@db:5432/file_storage
      AUTH_SERVICE_URL: http://auth:5001
      HOST: 0.0.0.0
      PORT: 5000
      SECRET_KEY: your-secret-key-here
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_started

volumes:
  postgres_data: